### ISSUE TITLE
Optional Visualization component

### ISSUE THREAD

**Issue by andavarv** [aws-solutions/aws-centralized-logging#49]
** Make visualization components are optional **
Thanks for the team providing centralized logging solution.  Is there any way to turn off the visualization component from the template.  We want to test it with Log indexing, so we would like to deploy the log ingestion and indexing components. 

Please let me know. 

Thanks

**Comment by groverlalit** [comment]
We are not adding new features because we recently launched the [Centralized Logging with OpenSearch](https://aws.amazon.com/solutions/implementations/centralized-logging-with-opensearch/) solution, which helps you quickly build a centralized log analytics platform. We recommend migrating to this new solution if all of the following are true:

    You currently use the Centralized Logging on AWS solution
    You aren't using AWS GovCloud (US) Region deployments
    You aren't using cross-Region logging features

To migrate to the new solution, follow the steps outlined in the Centralized Logging on AWS [implementation guide](https://docs.aws.amazon.com/solutions/latest/centralized-logging-on-aws/migrate-to-new-solution.html).
